export const YANGON_TOWNSHIPS = [
  'Ahlone',
  'Bahan',
  'Botahtaung',
  'Dagon',
  'Dagon Seikkan',
  'Dala',
  'Dawbon',
  'East Dagon',
  'Hlaing',
  'Hlaing Thar Yar',
  'Hlegu',
  'Hmawbi',
  'Insein',
  'Kamayut',
  'Kyauktada',
  'Kyeemyindaing',
  'Lanmadaw',
  'Latha',
  'Mayangone',
  'Mingalar Taung Nyunt',
  'Mingalardon',
  'Naypyitaw',
  'North Dagon',
  'North Okkalapa',
  'Pabedan',
  'Pazundaung',
  'Sanchaung',
  'Shwepyithar',
  'South Dagon',
  'South Okkalapa',
  'Tamwe',
  'Thaketa',
  'Thanlyin',
  'Thingangyun',
  'Thonegwa',
  'Yankin',
] as const;

export type YangonTownship = typeof YANGON_TOWNSHIPS[number];