project_id = "rtbkhrenswgzhuzltpgd"

[functions.create-customer-order]
verify_jwt = false

[functions.kbzpay-auto-login]
verify_jwt = false

[functions.kbzpay-link-customer]
verify_jwt = false

[functions.kbzpay-create-payment]
verify_jwt = true

[functions.kbzpay-webhook]
verify_jwt = false
