project_id = "rtbkhrenswgzhuzltpgd"

[functions.create-customer-order]
verify_jwt = false

[functions.kbzpay-auto-login]
verify_jwt = false

[functions.kbzpay-link-customer]
verify_jwt = false

[functions.kbzpay-create-payment]
verify_jwt = false

[functions.kbzpay-webhook]
verify_jwt = false

[functions.client-diag]
verify_jwt = false

[functions.kbzpay-query-order]
verify_jwt = false

[functions.create-order-intent]
verify_jwt = false

[functions.kbzpay-reconcile-cron]
verify_jwt = false
