// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtbkhrenswgzhuzltpgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0YmtocmVuc3dnemh1emx0cGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc2MDQ5MzUsImV4cCI6MjA4MzE4MDkzNX0.LCiLmrWtv-i1Ko8I4QXjbOYTRXrF8aqK_EATqfcXQmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    // No-op lock: bypass Navigator LockManager which hangs in KBZ Pay's WebView.
    // Safe here — the Mini App is single-tab and auth ops are already serialized
    // by our own guards (running.current + globalRanOnce in useKbzAutoLogin).
    lock: (_name, _acquireTimeout, fn) => fn(),
  }
});